/-
OnlineIssuance^LC - strict c.e. comparator boundary.

This module executes the next gate left by `OnlineIssuance.Comparator`: the
strict c.e. / partial-generation tier. It deliberately stays in core Lean, so
the model is a c.e.-presentation model:

- `CEEnumerator alpha := Nat -> Option alpha` emits zero or one value at each
  stage. `none` represents no output at that stage, so enumeration order and
  non-output are visible.
- It does NOT formalize recursive-function theory. There is no universal
  machine, s-m-n theorem, partial recursive code predicate, or proof that an
  enumerator itself is computable.

The result is the load-bearing c.e. ceiling:

1. finite-prefix freshness survives: against any finite observed prefix of a
   c.e. stream, `freshName` produces a name outside that prefix;
2. whole-c.e. positive escape fails: any proposed candidate is generated by
   its singleton c.e. enumerator, so no candidate can escape all c.e.
   enumerators.

This is a bounded no-go, not a promotion. It preserves the E121 boundary:
`OnlineIssuance^LC` remains class-relative; external Platonist completion and
physical source issuance are not modeled.
-/

import OnlineIssuance.Comparator

namespace OnlineIssuance

universe u v

/-! ## c.e.-presentation model -/

/-- A c.e.-style presentation: at each stage, either emit one value or emit
nothing. This captures stage order and non-output, but not computability of
the enumerator itself. -/
abbrev CEEnumerator (alpha : Type u) := Nat -> Option alpha

/-- A value is generated by an enumerator if it appears at some stage. -/
def CEGenerates {alpha : Type u} (E : CEEnumerator alpha) (a : alpha) : Prop :=
  Exists fun n => E n = some a

/-- The singleton c.e. enumerator for a value. -/
def singletonCE {alpha : Type u} (a : alpha) : CEEnumerator alpha :=
  fun n =>
    match n with
    | 0 => some a
    | Nat.succ _ => none

/-- Every value is generated by its singleton c.e. enumerator. -/
theorem singletonCE_generates {alpha : Type u} (a : alpha) :
    CEGenerates (singletonCE a) a :=
  Exists.intro 0 rfl

/-- Every constructed output is absorbed by a c.e. enumerator chosen after the
construction output is known. This is the strict c.e. version of the
fixed-family absorption warning: a positive "escapes all c.e. generators"
claim has the wrong quantifier order. -/
theorem construction_output_ce_absorbed {alpha : Type u} {beta : Type v}
    (construct : beta -> alpha) (b : beta) :
    Exists fun E : CEEnumerator alpha => CEGenerates E (construct b) :=
  Exists.intro (singletonCE (construct b)) (singletonCE_generates (construct b))

/-- Whole-c.e. escape is impossible in this presentation model. Any proposed
candidate is generated by its singleton enumerator. -/
theorem no_absolute_ce_escape {alpha : Type u} :
    Not (Exists fun a : alpha =>
      forall E : CEEnumerator alpha, Not (CEGenerates E a)) := by
  intro h
  rcases h with ⟨a, ha⟩
  exact ha (singletonCE a) (singletonCE_generates a)

/-! ## finite-prefix escape still survives -/

/-- Values emitted strictly before stage `n`, newest first. -/
def prefixValues {alpha : Type u} (E : CEEnumerator alpha) : Nat -> List alpha
  | 0 => []
  | Nat.succ n =>
      match E n with
      | some a => a :: prefixValues E n
      | none => prefixValues E n

/-- If an enumerator emits at stage `n`, the value appears in the next prefix. -/
theorem emitted_in_next_prefix {alpha : Type u}
    (E : CEEnumerator alpha) (n : Nat) (a : alpha)
    (h : E n = some a) :
    a ∈ prefixValues E (n + 1) := by
  simp [prefixValues, h]

/-- The fresh name against a finite observed c.e. prefix. -/
def ceFreshAtStage (E : CEEnumerator String) (n : Nat) : String :=
  freshName (prefixValues E n)

/-- Prefix-level escape survives: after seeing only a finite prefix of a c.e.
stream, the length-fresh name is not in that prefix. -/
theorem ce_prefix_fresh_escape (E : CEEnumerator String) (n : Nat) :
    ceFreshAtStage E n ∉ prefixValues E n :=
  freshName_not_mem (prefixValues E n)

/-- The same prefix-fresh output is nevertheless absorbed by its singleton
c.e. enumerator at the whole-family level. -/
theorem ce_prefix_escape_absorbed (E : CEEnumerator String) (n : Nat) :
    CEGenerates (singletonCE (ceFreshAtStage E n)) (ceFreshAtStage E n) :=
  singletonCE_generates (ceFreshAtStage E n)

/-! ## semantic-candidate ceiling -/

/-- Semantic candidates from the total-family comparator. This carries the
same object as `SemFamily`'s members: total Boolean predicates over naturals. -/
abbrev SemCandidate := Nat -> Bool

/-- If arbitrary semantic candidates are allowed as c.e. outputs, whole-c.e.
escape is still impossible: the candidate's singleton enumerator absorbs it.
This is the precise obstruction to strengthening E121's `diagSem_escapes`
into a positive c.e.-tier theorem without adding a computability discipline
that rules out after-the-fact singleton naming. -/
theorem no_absolute_semantic_ce_escape :
    Not (Exists fun f : SemCandidate =>
      forall E : CEEnumerator SemCandidate, Not (CEGenerates E f)) :=
  no_absolute_ce_escape

end OnlineIssuance
