#!/usr/bin/env python3
"""Candidate audit for emergent gauge/topological sector claims.

The candidate is physically serious because it has strong effective-algebra
language. This fixture asks whether that language is source-owned issuance or
whether it factors through a fixed microscopic platform plus an effective
projection.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import completion_class_v1 as cc


CANDIDATE_STATUS = "CANDIDATE_KILLED_FIXED_PLATFORM_EFFECTIVE_GAUGE"
COMPLETION_WITNESS_ID = "fixed_platform_effective_gauge_completion"
COMPLETION_FAMILIES = (
    "fixed_source",
    "boundary_condition",
    "resource_capability",
    "observer_information_access",
    "relabel_gauge",
)


@dataclass(frozen=True)
class AdapterField:
    field_id: str
    supplied: bool
    value: str
    finding: str


@dataclass(frozen=True)
class WitnessGate:
    gate_id: str
    source_passed: bool
    effective_signal: bool
    finding: str


def adapter_fields() -> tuple[AdapterField, ...]:
    return (
        AdapterField(
            "Gamma_n",
            True,
            "fixed microscopic atom/qubit platform, geometry, drive, and measurement context",
            "The source context is real but already includes the fixed platform.",
        ),
        AdapterField(
            "Adm_n",
            False,
            "low-energy/effective gauge-sector predicate",
            (
                "The admissibility predicate is supplied by the effective "
                "description or experimental protocol, not generated by the source."
            ),
        ),
        AdapterField(
            "e_n",
            True,
            "emergent gauge/topological sector event",
            "The candidate has a concrete before/after effective-sector trace.",
        ),
        AdapterField(
            "w_n",
            True,
            "string-breaking, gauge-invariance, edge-mode, or sector-marker record",
            "The witness is a preserved observation, not yet a source-law witness.",
        ),
        AdapterField(
            "Gamma_n_plus_1",
            False,
            "same microscopic source viewed through an effective sector",
            (
                "The successor context is a projected or constrained view of the "
                "same fixed platform rather than a source-owned new algebra."
            ),
        ),
        AdapterField(
            "tau_n",
            True,
            "experimental and model-comparison record of the sector marker",
            "Record preservation is available and is not the blocking field.",
        ),
    )


def witness_gates() -> tuple[WitnessGate, ...]:
    return (
        WitnessGate(
            "W1_non_isomorphic_algebra",
            False,
            True,
            (
                "Effective algebra or sector language appears, but it is not "
                "shown to be non-isomorphic source algebra growth rather than a "
                "low-energy or projected description of fixed microscopic degrees."
            ),
        ),
        WitnessGate(
            "W2_new_admissibility_predicate",
            False,
            False,
            (
                "The predicate is defined by the protocol, energy window, "
                "measurement pattern, or modeler's gauge language."
            ),
        ),
        WitnessGate(
            "W3_construction_space_growth",
            False,
            False,
            (
                "The construction space is a prepared platform plus control schedule, "
                "not a source-generated new construction grammar."
            ),
        ),
        WitnessGate(
            "W4_perturbation_non_factorization",
            False,
            False,
            (
                "Perturbations still factor through fixed platform dynamics, "
                "low-energy restriction, measurement/dissipation schedule, or "
                "coarse-graining."
            ),
        ),
        WitnessGate(
            "W5_record_preservation",
            True,
            True,
            "The sector markers and before/after records can be preserved.",
        ),
        WitnessGate(
            "W6_gauge_access_language_absorption",
            False,
            False,
            (
                "Gauge, access, effective-description, and relabeling absorption "
                "are not defeated."
            ),
        ),
    )


def fixed_source_rival() -> dict[str, Any]:
    return {
        "rival_id": "fixed_microscopic_platform_effective_gauge_projection",
        "fixed_microscopic_platform": True,
        "fixed_control_or_measurement_schedule": True,
        "fixed_low_energy_or_effective_projection": True,
        "fixed_boundary_or_geometry": True,
        "record_trace_preserved": True,
        "reproduces_candidate_shape": True,
        "source_owned_new_algebra": False,
        "reason": (
            "The observed sector is reproduced as an effective, low-energy, "
            "measurement-shaped, or gauge-language view of a fixed microscopic "
            "system with preserved records."
        ),
    }


def completion_case() -> cc.CompletionCase:
    witness = cc.CompletionWitness(
        witness_id=COMPLETION_WITNESS_ID,
        family_ids=COMPLETION_FAMILIES,
        predeclared=True,
        outcome_independent=True,
        physically_admissible=True,
        reproduces_joint_trace=True,
        preserves_comparison_contract=True,
        quotient_respecting=True,
        certificate_verified=True,
    )
    nonfactorized = tuple(
        family_id
        for family_id in cc.PRIMITIVE_FAMILY_IDS
        if family_id not in set(COMPLETION_FAMILIES)
    )
    return cc.CompletionCase(
        case_id="emergent_gauge_sector_candidate_v0",
        represented_family_ids=cc.PRIMITIVE_FAMILY_IDS,
        verified_nonfactorization_family_ids=nonfactorized,
        witnesses=(witness,),
        composition_closure_declared=True,
    )


def missing_source_object() -> dict[str, Any]:
    return {
        "missing_object_id": "source_owned_non_isomorphic_gauge_algebra",
        "required": (
            "A native source law that creates a new observable, instrument, or "
            "gauge-sector algebra not representable as an effective projection, "
            "low-energy restriction, control schedule, boundary condition, access "
            "change, or relabeling of a fixed microscopic platform."
        ),
        "also_required": (
            "An internal anti-after-naming principle plus W4 perturbation "
            "non-factorization under the same preserved record trace."
        ),
    }


def run_candidate() -> dict[str, Any]:
    completion_decision = cc.classify_case(completion_case())
    source_fields = adapter_fields()
    gates = witness_gates()

    return {
        "fixture_id": "emergent_gauge_sector_candidate_v0",
        "source_artifacts": [
            "explorations/E149-physical-candidates-state-space-growth-intake-2026-07-07.md",
            "explorations/external-reports/2026-07-07-physical-candidates-state-space-growth.md",
            "COMPLETION-CLASS.md",
        ],
        "candidate_domain": "emergent_gauge_topological_sector_quantum_matter",
        "candidate_status": CANDIDATE_STATUS,
        "packet_admitted": False,
        "typed_action_2_packet": False,
        "native_source_law_supplied": False,
        "adapter_fields": [asdict(field) for field in source_fields],
        "blocking_adapter_fields": [
            field.field_id for field in source_fields if not field.supplied
        ],
        "witness_gates": [asdict(gate) for gate in gates],
        "effective_algebra_signal_present": True,
        "source_growth_core_passed": any(gate.source_passed for gate in gates[:3]),
        "absorber_controls_passed": all(gate.source_passed for gate in gates[3:]),
        "fixed_source_rival": fixed_source_rival(),
        "completion_class_version": "completion_class_v1",
        "completion_class_verdict": completion_decision["verdict"],
        "valid_completion_witness_ids": completion_decision["valid_witness_ids"],
        "absorbed_family_ids": completion_decision["absorbed_family_ids"],
        "unresolved_family_ids": completion_decision["unresolved_family_ids"],
        "missing_family_ids": completion_decision["missing_family_ids"],
        "composition_closure_declared": completion_decision[
            "composition_closure_declared"
        ],
        "exact_missing_source_object": missing_source_object(),
        "physical_source_issuance_established": False,
        "TI_C020_reopened": False,
        "claim_status_change": "none",
        "E177_modified": False,
        "cross_repo_implication": False,
        "next_required_test": (
            "another non-overlapping physical candidate with a source-owned "
            "transition law, or a proof that no effective-gauge candidate can "
            "supply the missing source-owned algebra object"
        ),
    }


def write_json(result: dict[str, Any], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("tests/artifacts/emergent_gauge_sector_candidate_v0_result.json"),
    )
    args = parser.parse_args()
    result = run_candidate()
    write_json(result, args.output)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
